### ISSUE TITLE
[AIP-30][Implement decrease in staking rewards]

### ISSUE THREAD

**Issue by thepomeranian** [aptos-foundation/AIPs#119]
# AIP-30 - Implement decrease in staking rewards

## Summary

This AIP proposes a 1.5% yearly decrease in staking rewards, which is part of the Aptos tokenomics requirement. 

Link to AIP: https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-30.md

**Comment by dylanschultzie** [comment]
@thepomeranian will this necessitate a governance vote to enact each reduction in staking rewards, or will it be automated and enacting after a certain amount of epochs?

This is a little unrelated, but is there a bonding curve to reach a desired amount of stakers? For example - right now, inflation is 7%. Let's say 10% of tokens are bonded, in theory that would mean the "effective" APR for delegators is 70% (that 7% inflation is divided amongst 10% of tokens rather than 100%).

**Comment by michelle-aptos** [comment]
@dylanschultzie the reduction will be automated at the end of every year after the governance vote passes

**Comment by xindingw** [comment]
> This is a little unrelated, but is there a bonding curve to reach a desired amount of stakers? For example - right now, inflation is 7%. Let's say 10% of tokens are bonded, in theory that would mean the "effective" APR for delegators is 70% (that 7% inflation is divided amongst 10% of tokens rather than 100%).

7% reward rate doesn't means total supply of APT will increase 7% every year. 7% is proportional to **total staked amount**.  For example, total supply is 1,000,000 and the staked amount is 800,000, this year at most 800,000 * 7% = 56,000 APT can be minted.

**Comment by sherry-x** [comment]
Proposal 36 was a SingleStep proposal but got submitted using MultiStep proposal code path, so even though it passed voting, the proposal cannot be resolved. 

We will be resubmitting a proposal 37 with a consistent MultiStep method and going through voting again.

**Comment by commanderu** [comment]
When is the review?
