### ISSUE TITLE
[AIP-32][Storage Deletion Refund]

### ISSUE THREAD

**Issue by msmouse** [aptos-foundation/AIPs#127]
# AIP 32 - Storage Deletion Refund

# Summary

Proposed is to refund part of storage fee (introduce in [API-17](https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-17.md)) paid for storage slot allocation to the original payer when a slot is freed by deletion.

Link to AIP: https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-32.md

**Comment by IriArt** [comment]
This looks very cool!

**Comment by Milkpartner** [comment]
That's cool.

**Comment by e99243506bigplay** [comment]
I wonder what is happening on final gas price if you are going repeat to upload 32k Move contract module.

**Comment by e99243506bigplay** [comment]
There is a situation:
Alice put a NFT on marketplace for sale, Bob is bought Alice's NFT, Question is, who got the Storage Deletion Refund?

**Comment by msmouse** [comment]
> Alice put a NFT on marketplace for sale, Bob is bought Alice's NFT, Question is, who got the Storage Deletion Refund?
Depending on how the contract is wrote, if transferring the NFT implicates moving to a new storage slot, the original payer will get the refund on transfer and who ever sent the transaction to make the transfer pays the storage fee to allocate the new slot.

**Comment by meetrick** [comment]
That's cool.

**Comment by davidiw** [comment]
Why do we have the knobs for refunds and what are the proposed values?

**Comment by msmouse** [comment]
@david The numbers are in the picture (as e.g. s) but tentatively: 90% refund if deletion happens within one day after creation, and then the refund ratio starts to degrade linearly for 30 days until 50%.

**Comment by elliottdehn** [comment]
I have a practical use-case for this, but it would require the refund to be returned to the one doing the clearing instead of the one that created the storage. We (Econia) maintain an exchange that features a limit order book. Each of these limit orders takes up storage, and can be "freed" upon being "filled" by any trader. If someone is creating thousands of small limit orders to clog up trading execution, which happens order-by-order until a fill size, then returning refunds to the attacker upon their orders being filled just gives them more ammunition to attack with! **There is a cost to "bother with" a piece of storage.** I would expect all or most of that cost to be refunded upon bothering with and freeing the storage.

So if we return a refund to the trader who filled the order then we, in theory, make it possible to execute trades of any size at ~constant cost: every order that we bother with provides a refund that allows us to continue, thereby defeating order book attacks and achieving maximum trading efficiency.

**Comment by msmouse** [comment]
@elliottdehn Thanks for the feedback. That's exactly what we look for via the AIP process! While the case you describe can be addressed by "billing accounts" described under the "Future potentials" section, it's not being implemented too soon, and that's why we are evaluating refunding to the deleter instead of the original payer as well. Stay tuned. (And keep the feedbacks coming! ❤️ )

**Comment by elliottdehn** [comment]
Thanks you @msmouse, can we know if/when there will be a decision made on this?

**Comment by msmouse** [comment]
@elliottdehn We update the AIP so that we refund to the deleter, we also will start with full refunds, putting the declining refund pending for discussion. Let us know if this works better.

**Comment by elliottdehn** [comment]
@msmouse Excellent! Happy to hear this, yes it works better. Nice to know the DOS risk that is refunding the original storer has been ruled out, which was going to prevent our ability to utilize the refund feature in our contracts. Thanks team!

**Comment by elliottdehn** [comment]
@msmouse I/we have a question about this feature: what is the maximum number of refunds offered to transactions? This matters because it affects the determination of a constant in our protocol which determines the maximum number of limit orders that can be processed one-by-one during a trade. In fact it's more likely that upon the volume of a price bucket not fitting a trade (can't be executed all together at once), and the maximum-size order in that bucket being less than N% of the remaining trade, we switch to a different mode of execution that relaxes some requirements in the interests of ensuring the whole trade can be executed. The N% kind of depends on the maximum number of refunds that can be obtained. Thanks.
