### ISSUE TITLE
[AIP-94][Discussion] Reduce stake lockup duration to 14 days and governance voting duration to 3 days per community vote

### ISSUE THREAD

**Issue by sherry-x** [aptos-foundation/AIPs#488]
# AIP Discussion

Aptos (APT), the layer 1 blockchain that we’re building upon, employs a Proof of Stake (PoS) consensus mechanism, wherein validators stake tokens to participate in network operations and governance.
Currently, Aptos has a 30-day lock-up period for staked tokens, one of the longest among layer 1 protocols. This duration aims to ensure network stability and robust on-chain governance. However, feedback from various stakeholders suggests that reducing this period might offer significant benefits.
As such, we’re proposing some possible implementation options for our community to consider. We conducted a survey within the community, and the winning option is to reduce the lock-up period to 14 days and the voting period to 3 days. This combination offers the best trade-offs between shorter staking lockup and providing ample time for the community to vote on governance proposals on Aptos.

Read more about it here: https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-94.md

**Comment by meetrick** [comment]
Reducing the unlock duration would provide significant benefits in terms of increased liquidity and operational efficiency. However, I believe further discussion is needed regarding the reduction of the governance voting duration, as there are already concerns raised by the foundation.

**Comment by sherry-x** [comment]
Hey @meetrick, could you please elaborate more on what's your concern for the voting duration? I have added a paragraph in the AIP to explain why these two parameters need to be tuned together, let me know if there's any questions https://github.com/aptos-foundation/AIPs/blob/main/aips/aip-94.md#why-updating-voting-duration-while-this-aip-is-focued-on-shoterning-the-lockup-duration

**Comment by meetrick** [comment]
@sherry-x First of all, thank you for updating the document. Through the document, I have understood the reason why the governance voting duration needs to be shortened in order to reduce the stake lockup duration. I understand that although shortening the voting duration doesn’t completely eliminate the issue, it aims to minimize it as much as possible. Is my understanding correct?

I just thought that a voting duration that is too short could reduce voter participation and limit the time available for proper verification. That’s why I believed the stake lockup duration and governance voting duration should be handled separately.

However, these issues can be improved by the foundation encouraging users to participate.

**Comment by sherry-x** [comment]
@meetrick Yes your understanding is correct. 

With this change, Foundation will focus more on communicating the AIPs when they get proposed at early stage, way before they get submitted to Mainnet for voting, to gather feedbacks from community and hear their thoughts. Similar like how we're discussing it here. There will be a much longer period of time of forming community support before the actual voting to address this issue. e.g. this AIP formed from a X poll done by Amnis team, once they got the support from the ecosystem, they wrote up this proposal, and we've been socializing this AIP for a while for community review, and then the final stage will be on-chain voting.

With that being said, your concern is still very valid, shorter voting period is still a risk of less participation, and could still result in proposal failure because not able to get enough vote. However we think this trade off at this stage is worth it, because we heard many feedback on the lockup time being too long. We're actively seeking ways to decouple the lockup time and governance voting time, so that we can adjust these two configuration independently.

**Comment by cryptomolot** [comment]
@sherry-x Thank you so much for this proposal. I have already voted [FOR it](https://explorer.aptoslabs.com/txn/1703389136/userTxnOverview?network=mainnet)


Reducing the lock-up period will allow regular users more flexibility with their $APT. Delegators will now be more "agile" while still benefiting from staking.

Additionally, reducing the voting period will enable the team to implement changes more quickly, and important proposals can be highlighted in advance so that the community doesn't miss them. That said, I believe active voting participants won't miss important updates one way or another. They either follow each one or don't follow at all.
