### ISSUE TITLE
[AIP-X][Discussion]

### ISSUE THREAD

**Issue by evilboyajay** [aptos-foundation/AIPs#49]
---
aip: 
title: Calling between move contracts 
author: evilboyajay
discussions-to:
Status: Draft
last-call-end-date:
type: Framework
created: 2023/01/22
updated:
requires:

---

# AIP-(TBD) - (Calling between move contracts )

## Summary

This AIP proposes one contract to call another contract directly without importing using the contract address and function.

## Motivation

While writing multisig move contracts on APTOS, I have not been able to dynamically call other smart contracts because of missing calling between the contract function. This limits the ability of smart contracts to interact with other smart contracts, which eventually impacts governance.

## Rationale

This AIP will provide the ability for smart contracts to dynamically call other contracts. This will enable the creation of more complex and modular smart contract systems like multisig contracts that can call other contracts dynamically when all the multi-sig owners sign the transaction. In the transaction, data, accounts, module name, and functions are passed as parameters to the contract.

## Specification

This is just an example if we make a function **call** which can call another contract functions, this is how we can make a transaction builder.
```rust
public fun call_contract(account: &signer, module_address: address, module_function: u8, parameters: vector<u8>){
  call(module_address,module_function,parameters)
}
```
Here, parameters are the parameter of functions that needs to be passed, 
module_address is the address of the contract,
module_function is the name of the function to be called. 

## Reference Implementation

https://docs.solana.com/developing/programming-model/calling-between-programs

https://solidity-by-example.org/delegatecall/

## Risks and Drawbacks

To be decided

## Future Potential

This can be used in governance systems, where the smart contract can manage the voting power and based on that it can execute the transactions to other modules.
## Suggested implementation timeline

To be decided

**Comment by e99243506bigplay** [comment]
module_function type is u64, how could you apply that for dynamic calling unknown function?

```
$ ./aptos move run --profile dev  --function-id 0x                                                                   
error: Invalid value "0x" for '--function-id <FUNCTION_ID>': Invalid arguments: FunctionId is not well formed.  Must be of the form <address>::<module>::<function>
```

**Comment by wrwg** [comment]
Hi @evilboyajay , thank you for the suggestion!

What you are asking for are EVM proxies, as far as I understand.

But Aptos supports code upgrade. Why do you still want to have proxies? I imagine there are some corner cases but for the majority, upgrade seems to be a much safer and easier way.

**Comment by evilboyajay** [comment]
Yes, the Aptos code is upgradeable. This is totally different from upgrading a contract. Here I am proposing a way where a contract can call another contract directly.
In Solana, we have cpi to call another Solana program directly. 

https://docs.solana.com/developing/programming-model/calling-between-programs

The implementation of CPI can be reviewed here 
https://github.com/coral-xyz/multisig/blob/master/programs/multisig/src/lib.rs#L186

**Comment by davidiw** [comment]
@evilboyajay, I think there is a bit to unravel here:
* Your examples of Solana look like these are all static declarations. That is these are defined at compile time. Move has seamless inter-module calling without requiring API helpers like `invoke`.
* Aptos has a rich on-chain Multisig account, see https://github.com/aptos-labs/aptos-core/blob/main/aptos-move/framework/aptos-framework/sources/multisig_account.move

I believe ultimately the best location for this discussion is not likely an AIP, because there's no proposal, this looks more like a feature request. Secondly, dynamic dispatch is intentionally not a part of Move due to the security implications.

If there are applications outside of governance and multisig that would benefit from this, it would be good to enumerate. Perhaps we can then place them in AptosCore as feature requests / exploratory endeavors.
